@echo off
TITLE YOU ARE AWESOME - INFO
ECHO: HELLO!
PAUSE
CLS
ECHO: THE "YOU ARE AWEESOME" HAVE BEEN CREATED BY:MARCOS
PAUSE
CLS
ECHO: RUNNING...
start https://github.com/SH0-ahacker/you_are_awesome/
